#!/bin/bash

# Grab the container IP
ADDR=$(/sbin/ifconfig eth0 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}')
echo "IP Address is: $ADDR"

# Check if a seed was provided
SEED=${SEED:=$ADDR}
echo "Seed is: $SEED"

#SNITCH=${SNITCH:-GossipingPropertyFileSnitch}
SNITCH=${SNITCH:-SimpleSnitch}
echo "Snitch: $SNITCH"

if [ ! -f /root/.cassconfig ]; then
    echo "Filling in the blanks inside cassandra.yaml"
    # Target files
    ENV_FILE=/opt/cassandra/conf/cassandra-env.sh
    # Add heap settings
    echo MAX_HEAP_SIZE="4G" >> $ENV_FILE
    echo HEAP_NEWSIZE="800M" >> $ENV_FILE
    touch /root/.cassconfig
fi
    SRC_CONF_FILE=/src/cassandra.yaml
    CONF_FILE=/opt/cassandra/conf/cassandra.yaml
    ( cat $SRC_CONF_FILE 
    # Add broadcast IPs
    echo "listen_address: $ADDR"
    echo "broadcast_rpc_address: $ADDR" 
    echo "rpc_address: 0.0.0.0" 
    # Add seed info
    echo "seed_provider:" 
    echo "  - class_name: org.apache.cassandra.locator.SimpleSeedProvider" 
    echo "    parameters:" 
    echo "      - seeds: \"$SEED\""
    echo "endpoint_snitch: $SNITCH" ) > $CONF_FILE

# Start server
cd /opt/cassandra
bin/cassandra -f
